---
title: "Land Use Model Outputs (fits)"
author: "Elisabeth Nelson"
date: "2023-03-31"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(readr)
library(readxl)
library(ggplot2)
library(tidyr)
library(tidyverse)
library(tsibble)
library(plotly)
library(lubridate)
library(TSDT)
library(rgeos) 
library(maptools) 
library(spdep)  
library(ggmap)  
library(sf)
library(rgdal)
library(gridExtra)
```

```{r, include=FALSE}
## Base Model - Observed Cases
base_model_final <- readRDS("base_model_final.RDS")

base_model_final_2 <- base_model_final %>%
  mutate(year = as_factor(year)) %>%
  filter(VARNAME_2 != "Kien Hai", 
         VARNAME_2 != "Phu Quoc") %>%
  distinct(year, month, VARNAME_2, NAME_1, ENGTYPE_2, .keep_all = T) %>%
  mutate(Dominant_LU_index_1 = if_else(is.na(Dominant_LU_index_1), 0, Dominant_LU_index_1)) %>%
  arrange(month, year, VARNAME_2)

```

## Land Use Model Fitted Values 0-144
```{r, message=FALSE, warning=FALSE, tidy=TRUE, echo=FALSE}
#base_model_0 <- base_model_final_2 %>%
#  mutate(year = unfactor(year), 
#         date = as.Date(paste(year, month, '01', sep='-'))) %>%
#  filter(date <= (as.Date('2006-12-01' ) %m+% months(0))) %>%
#  mutate(t = row_number())

# model output
#post_fit_0 <- readRDS("Data_2/posterior_fit_values_0 (2).rds")

#post_fit_0_df <- as.data.frame(post_fit_0)[1,]
#post_fit_0_df <- post_fit_0_df  %>%
#  pivot_longer(cols = starts_with("var")) %>%
#  mutate(t = row_number())

# join to base model
#model_check <- left_join(base_model_0, post_fit_0_df, by = c("t" = "t"))

# calculate incidence
#model_check <- model_check %>%
#  group_by(VARNAME_2, year, month) %>%
#  mutate(monthly_inc = (m_DHF_cases/pop)*100,000, 
#         fitted_inc = (value/pop)*100,000)

# calculate MAE
#mod1_mae <- model_check %>%
#  filter(date == (as.Date('2006-12-01' ) %m+% months(0))) %>%
#  mutate(mae = abs(monthly_inc - fitted_inc))

for(i in 80:144){
  N_advance <- i

display.func <- function(N_advance){
  # observed cases
  base_model <- base_model_final_2 %>%
  mutate(year = unfactor(year), 
         date = as.Date(paste(year, month, '01', sep='-'))) %>%
  filter(date <= (as.Date('2006-12-01' ) %m+% months(N_advance))) %>%
  mutate(t = row_number())
  
  # model output
  land_use_fit <- readRDS(paste0("Data/land_use/land_use_results/post_fit_lu_", N_advance, ".rds"))
  
  land_use_df <- as.data.frame(land_use_fit)
  land_use_df <- land_use_df  %>%
  mutate(t = row_number())
  
  # join to base model
  model_check <- left_join(base_model, land_use_df, by = c("t" = "t"))

  # calculate incidence
  model_check <- model_check %>%
    group_by(VARNAME_2, year, month) %>%
    mutate(monthly_inc = (m_DHF_cases/pop)*100,000,
           monthly_inc = if_else(is.na(monthly_inc), 0, monthly_inc),
         fitted_inc = (land_use_fit/pop)*100,000, 
         fitted_inc = if_else(is.na(fitted_inc), 0, fitted_inc))
  
  
  #plot1 <- model_check %>%
  #filter(VARNAME_2 == "Vinh Hung") %>%
  #ggplot()+
  #geom_point(aes(date, monthly_inc), col = "black")+
  #geom_point(aes(date, fitted_inc), color = "red")+
  #theme_classic()+
  #xlab("Date")+
  #ylab("Monthly Incidence")+
  #labs(title = paste0("LU Vinh Hung", N_advance), subtitle = "Incidence per 100,000")
  
  #plot2 <- model_check %>%
  #filter(VARNAME_2 == "Cai Lay District") %>%
  #ggplot()+
  #geom_point(aes(date, monthly_inc), col = "black")+
  #geom_point(aes(date, fitted_inc), color = "red")+
  #theme_classic()+
  #xlab("Date")+
  #ylab("Monthly Incidence")+
  #labs(title = paste0("LU Cai Lay District", N_advance), subtitle = "Incidence per 100,000")
  
  #plot3 <- model_check %>%
  #filter(VARNAME_2 == "Phu Tan An Giang") %>%
  #ggplot()+
  #geom_point(aes(date, monthly_inc), col = "black")+
  #geom_point(aes(date, fitted_inc), color = "red")+
  #theme_classic()+
  #xlab("Date")+
  #ylab("Monthly Incidence")+
  #labs(title = paste0("LU Phu Tan An Giang", N_advance), subtitle = "Incidence per 100,000")
  
  #plot4 <- model_check %>%
    #ggplot()+
    #geom_point(aes(monthly_inc, fitted_inc))+
    #geom_line(aes(monthly_inc, fitted_inc))+
    #theme_classic()+
    #xlab("Observed Monthly Incidence")+
    #ylab("Fitted Monthly Incidence")+
    #labs(title = paste0("LU Observed vs. Fitted Monthly Incidence", N_advance))
   
  #plot5 <- model_check %>%
    #filter(date == (as.Date('2006-12-01' ) %m+% months(N_advance))) %>%
    #ggplot()+
    #geom_point(aes(sqrt(monthly_inc), sqrt(fitted_inc)))+
    #theme_classic()+
    #xlab("Observed Monthly Incidence (sqrt)")+
    #ylab("Fitted Monthly Incidence (sqrt)")+
    #labs(title = paste0("LU Observed vs. Fitted Monthly Incidence", N_advance))
    
  # calculate MAE
  mae_df <- model_check %>%
  filter(date == (as.Date('2006-12-01' ) %m+% months(N_advance))) %>%
  mutate(mae = abs(monthly_inc - fitted_inc))
  saveRDS(mae_df, paste0("Data_2/LU_MAE_df", N_advance, ".rds"))
  
  #p1 <- grid.arrange(plot1, plot2, plot3, plot4, plot5, ncol = 2, nrow = 3)
  #return(p1)
  return(0)
}

display.func(i)

}

#lapply(1:2, display.func)
```


## MAE Maps for Base Model 0-144
```{r, message=FALSE, warning=FALSE, tidy=TRUE, echo=FALSE, fig.show='hold', out.width="50%"}
for(i in 0:144){
  N_advance <- i
  mae.map.func <- function(N_advance){
    # MAE data
    MAE <- readRDS(paste0("Data_2/LU_MAE_df", N_advance, ".rds"))

    # map
    map <- ggplot(MAE)+
      geom_sf(aes(fill = mae, geometry = geometry), lwd = 0)+
      viridis::scale_fill_viridis(option = "viridis", 
                                  direction = -1, 
                                  name = "MAE", 
                                  oob = scales::squish)+
      theme(axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks = element_blank(),
            panel.background = element_rect(fill = "white", color = NA))+
      labs(title = paste0("LU Mean Absolute Error, ", N_advance), 
          subtitle = "Observed incidence - fitted incidence")
    
    return(map)
  }
  plot(mae.map.func(i))
}  
#lapply(0:144, mae.map.func)
```




## Get MAE
```{r, message=FALSE, warning=FALSE, tidy=TRUE, echo=FALSE}

mae_merged_df <- do.call(rbind, 
                         lapply(list.files('/Users/zoe/Documents/Yale EMD/Rotation 1/Dengue - Vietnam/dengue_exploration/Data_2/MAE', 
                        recursive = TRUE, full.names = TRUE), readRDS))
saveRDS(mae_merged_df, "lu_model_mae.rds")

mae <- mae_merged_df %>%
  group_by(VARNAME_2) %>%
  summarize(mae_avg = mean(mae), 
            geometry = geometry) %>%
  distinct(VARNAME_2, .keep_all = T)

ggplot(mae)+
      geom_sf(aes(fill = mae_avg, geometry = geometry), lwd = 0)+
      viridis::scale_fill_viridis(option = "viridis", 
                                  direction = -1, 
                                  name = "MAE", 
                                  oob = scales::squish)+
      theme(axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks = element_blank(),
            panel.background = element_rect(fill = "white", color = NA))+
      labs(title = "Mean Absolute Error", 
           subtitle = "By district, using monthly incidence per 100,000 persons")

mae_merged_df %>%
  group_by(VARNAME_2, month) %>%
  summarize(mae_avg = mean(mae), 
            geometry = geometry) %>%
  distinct(VARNAME_2, month, .keep_all = T) %>%
  ggplot()+
      geom_sf(aes(fill = mae_avg, geometry = geometry), lwd = 0)+
      facet_wrap(~factor(month))+
      viridis::scale_fill_viridis(option = "viridis", 
                                  direction = -1, 
                                  name = "MAE", 
                                  oob = scales::squish)+
      theme(axis.text.x = element_blank(),
            axis.text.y = element_blank(),
            axis.ticks = element_blank(),
            panel.background = element_rect(fill = "white", color = NA))+
      labs(title = "Mean Absolute Error", 
           subtitle = "By district and month, using monthly incidence per 100,000 persons")

```

## Get single MAE estimate
```{r}

MAE_full <- readRDS("lu_model_mae.rds")

MAE_full %>%
  ungroup() %>%
  summarize(mae_avg = mean(mae))

```